services:

  app:
    build: .
    # image: gofrendi/app-mock2
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - APP_DB_CONNECTION_STRING=root:toor@tcp(db:3306)/merdeka?charset=utf8mb4&parseTime=True&loc=Local
      - APP_PORT=8080

  db:
    image: bitnami/mysql
    # selalu restart container ini, kecuali container nya di stop
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=merdeka
    healthcheck:
      # perintah untuk memastikan bahwa mysql sudah ready
      test: ["CMD", "mysql", "-u", "root",  "-ptoor", "-e", "show schemas"]
      interval: 10s 

  adminer:
    image: adminer
    restart: unless-stopped
    ports: # host:container
      - 8081:8080
