---
name: Deploy
on:
  push:
    branches:
      - master

jobs:

  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/alta-merdeka-mocking-2
          git pull origin master
          docker-compose down
          docker-compose up -d